{{- if .Values.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: crabserver
  labels:
    app: crabserver
  namespace: crab
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    sudo cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    exec /data/entrypoint.sh /data/run.sh
{{- end }}
