---
environment: "test"

image:
  path: registry.cern.ch/cmscrab/crabserver
  pullPolicy: IfNotPresent
  tag: "pypi-devthree-1715075269"
  command:
    - /data/entrypoint.sh
  args:
    - /bin/bash
    - -c
    - |
        sudo cp /host/etc/grid-security/* /etc/grid-security \
        && echo 'INFO Files in /etc/grid-security' \
        && ls -lahZ /etc/grid-security \
        && /data/run.sh

# disable liveness/readiness
# https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key
livenessProbePreProd: null
readinessProbePreProd: null
readinessProbe: null
livenessProbe: null
